package by.htp3.hotel.controller;

public enum CommandName {
	LOGINATION, REGISTRATION, CHANGE_LANGUAGE, SHOW_FREE_ROOMS,
	ADD_NEW_ROOM, BOOKING, GET_FREE_ROOMS, CHANGE_ACCOUNT, SHOW_ALL_ROOMS, DELETE_ROOM 

}
